### ISSUE TITLE
KeyError: 'body'

### ISSUE THREAD

**Issue by Jai-Gogineni** [ambertests/charles_to_postman#4]
- Python 2.7.16 (default, Mar  4 2019, 09:01:38) - Version
I am having the following issue with files 
- **charles_to_postman.py**
- **charles_to_postman_27.py**

Command - `python charles_to_postman_27.py -i dynamic.chlsj -o OUTPUT -n dyna`

Issue - 
`  File "charles_to_postman_27.py", line 241, in <module>
    convert_charles_to_postman(CHARLES_NODE))
  File "charles_to_postman_27.py", line 171, in convert_charles_to_postman
    body = {'mode': 'raw', 'raw': c_request['body']['text']}
KeyError: 'body'`

Command - `python charles_to_postman.py -i dynamic.chlsj -o OUTPUT -n dyna`
issue- 
`
Traceback (most recent call last):
  File "charles_to_postman.py", line 241, in <module>
    convert_charles_to_postman(CHARLES_NODE))
  File "charles_to_postman.py", line 171, in convert_charles_to_postman
    body = {'mode': 'raw', 'raw': c_request['body']['text']}
KeyError: 'body'
`

Am I missing anything  ?

**Comment by ambertests** [comment]
Judging from the error, one of your charles requests doesn't have a body. Can you narrow down the request that is failing?

________________________________

**Comment by Jai-Gogineni** [comment]
Hi, Yes! It was missing body. It worked fine once I removed from charles.

Thank you.
